version: "3.8"
services:
  gulp:
    build: .    
    ports:
      - '3000:3000'
    command: gulp
    volumes:
      - ./gulpfile.js:/app/gulpfile.js
      - ./src:/app/src
      - ./dist:/app/dist
  
